export const USER_REAUTH_SUCCESS = 'USER_REAUTH_SUCCESS';
export const REMOVE_USER = 'REMOVE_USER';

export const FETCH_VOTES_START = 'FETCH_VOTES_START';
export const FETCH_VOTES_SUCCESS = 'FETCH_VOTES_SUCCESS';
export const FETCH_VOTES_FAILURE = 'FETCH_VOTES_FAILURE';
export const REMOVE_VOTES = 'REMOVE_VOTES';
export const EDIT_VOTE = 'EDIT_VOTE';
export const NEW_VOTE = 'NEW_VOTE';

export const FETCH_TEAMS_START = 'FETCH_TEAMS';
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';
export const FETCH_TEAMS_FAILURE = 'FETCH_TEAMS_FAILURE';

export const FETCH_GAMES_START = 'FETCH_GAMES_START';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';
export const SELECT_GAME = 'SELECT_GAME';


export const FETCH_GAME_COMMENTS_START = 'FETCH_GAME_COMMENTS_START';
export const FETCH_GAME_COMMENTS_SUCCESS = 'FETCH_GAME_COMMENTS_SUCCESS';
export const FETCH_GAME_COMMENTS_FAILURE = 'FETCH_GAME_COMMENTS_FAILURE';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_GAME_COMMENT = 'DELETE_GAME_COMMENT';
export const EDIT_GAME_COMMENT = 'EDIT_GAME_COMMENT';

export const AUTH_START = 'AUTH_START';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_NUM_VOTES_START = 'FETCH_NUM_VOTES_START';
export const FETCH_NUM_VOTES_SUCCESS = 'FETCH_NUM_VOTES_SUCCESS';
export const FETCH_NUM_VOTES_FAILURE = 'FETCH_NUM_VOTES_FAILURE';
export const ADD_NUM_VOTE = 'ADD_NUM_VOTE';
export const EDIT_NUM_VOTE = 'EDIT_NUM_VOTE';

export const FETCH_GAME_TEAM_STATS = 'FETCH_GAME_TEAM_STATS';
export const FETCH_GAME_TEAM_STATS_START = 'FETCH_GAME_TEAM_STATS_START';
export const FETCH_GAME_TEAM_STATS_SUCCESS = 'FETCH_GAME_TEAM_STATS_SUCCESS';
export const FETCH_GAME_TEAM_STATS_FAILURE = 'FETCH_GAME_TEAM_STATS_FAILURE';

export const FETCH_USER_STATS_START = 'FETCH_USER_STATS_START';
export const FETCH_USER_STATS_SUCCESS = 'FETCH_USER_STATS_SUCCESS';
export const FETCH_USER_STATS_FAILURE = 'FETCH_USER_STATS_FAILURE';
