export const USER_REAUTH = 'USER_REAUTH';
export const USER_REAUTH_SUCCESS = 'USER_REAUTH_SUCCESS';
export const REMOVE_USER = 'REMOVE_USER';
export const FETCH_VOTES_START = 'FETCH_VOTES_START';
export const FETCH_VOTES_SUCCESS = 'FETCH_VOTES_SUCCESS';
export const FETCH_VOTES_FAILURE = 'FETCH_VOTES_FAILURE';
export const REMOVE_VOTES = 'REMOVE_VOTES';
export const FETCH_TEAMS_START = 'FETCH_TEAMS';
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';
export const FETCH_TEAMS_FAILURE = 'FETCH_TEAMS_FAILURE';
export const FETCH_GAMES_START = 'FETCH_GAMES_START';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';

export const NEW_VOTE = 'NEW_VOTE';
export const EDIT_VOTE = 'EDIT_VOTE';

export const FETCH_GAME_COMMENTS_START = 'FETCH_GAME_COMMENTS_START';
export const FETCH_GAME_COMMENTS_SUCCESS = 'FETCH_GAME_COMMENTS_SUCCESS';
export const FETCH_GAME_COMMENTS_FAILURE = 'FETCH_GAME_COMMENTS_FAILURE';